// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUKCTwfPVraL1N7Vee30RWDQTJ4Xp1MPM',
    appId: '1:288202459300:web:f6b6a2c23feda52740be31',
    messagingSenderId: '288202459300',
    projectId: 'shield-51993',
    authDomain: 'shield-51993.firebaseapp.com',
    storageBucket: 'shield-51993.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO7l2imB5mFDt6OJRPFfzkXkT4-onxYgY',
    appId: '1:288202459300:android:4035b4b408cac4e440be31',
    messagingSenderId: '288202459300',
    projectId: 'shield-51993',
    storageBucket: 'shield-51993.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbsDWs8cAxlV05Sbu_boNgTzjibi8__uE',
    appId: '1:288202459300:ios:d38d337eab5a147740be31',
    messagingSenderId: '288202459300',
    projectId: 'shield-51993',
    storageBucket: 'shield-51993.firebasestorage.app',
    iosBundleId: 'com.example.shieldCommandCenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbsDWs8cAxlV05Sbu_boNgTzjibi8__uE',
    appId: '1:288202459300:ios:d38d337eab5a147740be31',
    messagingSenderId: '288202459300',
    projectId: 'shield-51993',
    storageBucket: 'shield-51993.firebasestorage.app',
    iosBundleId: 'com.example.shieldCommandCenter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUKCTwfPVraL1N7Vee30RWDQTJ4Xp1MPM',
    appId: '1:288202459300:web:22c6b33945019ef240be31',
    messagingSenderId: '288202459300',
    projectId: 'shield-51993',
    authDomain: 'shield-51993.firebaseapp.com',
    storageBucket: 'shield-51993.firebasestorage.app',
  );
}
